using Autodesk.AutoCAD.Geometry;

namespace ckx
{
    public class myStair
    {
        public Point3d point { get; set; }
        public int Num { get; set; }
        public double FloorWidth { get; set; }
        public double FloorHeight { get; set; }
        public double LtW { get; set; }
        public double LtH { get; set; }

        public double LTN { get; set; }
        public double ExtW { get; set; }
        public double ExtW2 { get; set; }
        public double ExtH { get; set; }
        public double Cover { get; set; }
        public double Sh { get; set; }
        public double SW { get; set; }

    }
}
